### PR TITLE
removed upload text component

### PR DESCRIPTION
**Pull request by frankmfernandez**
removed upload text component

### CODE REVIEW

**Review by jmourell — COMMENTED** [review]
Active Experience also has a part that is looking at what media type that could be removed

**Review by wilandrade — CHANGES_REQUESTED** [review]
Please see Julian's comments.

**Comment by frankmfernandez** [comment]
> Please see Julian's comments.

should be fixed please check

**Review by jmourell — APPROVED** [review]
Looks good!

**Pull request merged**
